# #####################################################################
# Automatically generated by qmake (2.01a) Tue Jan 19 19:32:31 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Parser.h \
    Parser.cpp \
    ../client/client.h
SOURCES += Calculator.cpp \
    Parser.cpp \
    ../client/client.cpp

QT += network
